spring:
  datasource:
     url: jdbc:mysql://192.168.2.185:3306/aucn?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
     username: car
     password: password
     driverClassName: com.mysql.jdbc.Driver
     initialize: true
     #连接池配置
     initialSize: 10
     minIdle: 5
     maxActive: 40
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     testWhileIdle: true
     testOnBorrow: true
     testOnReturn: false
     type: com.alibaba.druid.pool.DruidDataSource
     min-evictable-idle-time-millis: 300000
     validation-query: SELECT 1
     test-while-idle: true
     test-on-borrow: true
     test-on-return: false
     pool-prepared-statements: true
     max-pool-prepared-statement-per-connection-size: 20
     filters: stat,wall,log4j
     connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  cache:
    type: REDIS
  redis:
    database: 8
    host: 192.168.2.195
    port: 6379
    password: 5DX@hzgs
    timeout: 1200
    pool:
      max-active: 50
      max-wait: 600
      max-idle: 20
      min-idle: 5

logging.level.com.ljx.demo.mapper: debug
